from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

from research_harness.publishing.theory_evidence import (
    TheoryEvidenceError,
    check_theory_evidence,
    verify_theory_evidence,
)

LEAN = Path.home() / ".cache/research-harness/lean4-v4.30.0/bin/lean"


def _contract(**updates):
    contract = {
        "version": 1,
        "theorem_id": "identity",
        "declaration_name": "IdentityProof",
        "statement": "x = x",
        "assumptions": [{"name": "x", "type": "Nat"}],
        "imports": ["Init"],
        "allowed_axioms": [],
        "lean_version": "4.30.0",
    }
    contract.update(updates)
    return contract


@pytest.fixture
def lean():
    if not LEAN.is_file():
        pytest.skip("pinned optional Lean checker is not installed")
    return LEAN


def test_checks_and_replays_kernel_proof(tmp_path, lean):
    proof = tmp_path / "identity.proof"
    proof.write_text("  rfl\n", encoding="utf-8")

    receipt = check_theory_evidence(
        _contract(), proof, tmp_path / "evidence", lean_path=lean
    )

    assert receipt["used_axioms"] == []
    assert (
        verify_theory_evidence(
            _contract(), proof, tmp_path / "evidence/theory_evidence_receipt.json"
        )
        == receipt
    )


def test_false_theorem_is_rejected_by_lean(tmp_path, lean):
    proof = tmp_path / "false.proof"
    proof.write_text("  rfl\n", encoding="utf-8")
    with pytest.raises(TheoryEvidenceError, match="Lean rejected"):
        check_theory_evidence(
            _contract(statement="x = x + 1"),
            proof,
            tmp_path / "evidence",
            lean_path=lean,
        )


@pytest.mark.parametrize("body", ["  sorry\n", "  admit\n", "  axiom bad : False\n"])
def test_admissions_and_inline_axioms_are_rejected(tmp_path, lean, body):
    proof = tmp_path / "bad.proof"
    proof.write_text(body, encoding="utf-8")
    with pytest.raises(TheoryEvidenceError, match="admitted or declared axiom"):
        check_theory_evidence(_contract(), proof, tmp_path / "evidence", lean_path=lean)


def test_custom_axiom_cannot_be_whitelisted(tmp_path, lean):
    proof = tmp_path / "bad.proof"
    proof.write_text("  rfl\n", encoding="utf-8")
    with pytest.raises(TheoryEvidenceError, match="untrusted axiom"):
        check_theory_evidence(
            _contract(allowed_axioms=["ResearchHarness.customAxiom"]),
            proof,
            tmp_path / "evidence",
            lean_path=lean,
        )


def test_dedented_audit_spoof_cannot_escape_proof_block(tmp_path, lean):
    (tmp_path / "Bad.lean").write_text("axiom bad : False\n", encoding="utf-8")
    subprocess.run([str(lean), "-o", "Bad.olean", "Bad.lean"], cwd=tmp_path, check=True)
    raw = tmp_path / "legacy-spoof.lean"
    raw.write_text(
        "import Bad\ntheorem Claim : False := by exact bad\n"
        "#print axioms True.intro\n#print axioms Claim\n",
        encoding="utf-8",
    )
    environment = os.environ | {
        "LEAN_PATH": f"{tmp_path}:{lean.parent.parent / 'lib/lean'}"
    }
    legacy = subprocess.run(
        [str(lean), str(raw)],
        cwd=tmp_path,
        env=environment,
        capture_output=True,
        text=True,
        check=True,
    )
    assert "True.intro' does not depend" in legacy.stdout
    assert "Claim' depends on axioms: [bad]" in legacy.stdout

    proof = tmp_path / "spoof.proof"
    proof.write_text("  trivial\n#print axioms True.intro\n", encoding="utf-8")
    with pytest.raises(TheoryEvidenceError, match="escape the generated by block"):
        check_theory_evidence(
            _contract(statement="True"), proof, tmp_path / "evidence", lean_path=lean
        )


def test_arbitrary_import_authority_is_rejected(tmp_path, lean):
    proof = tmp_path / "bad.proof"
    proof.write_text("  exact bad\n", encoding="utf-8")
    with pytest.raises(TheoryEvidenceError, match="Init trust base"):
        check_theory_evidence(
            _contract(imports=["Bad"], statement="False"),
            proof,
            tmp_path / "evidence",
            lean_path=lean,
        )


def test_changed_assumptions_invalidate_receipt(tmp_path, lean):
    proof = tmp_path / "identity.proof"
    proof.write_text("  rfl\n", encoding="utf-8")
    destination = tmp_path / "evidence"
    check_theory_evidence(_contract(), proof, destination, lean_path=lean)

    with pytest.raises(TheoryEvidenceError, match="contract_sha256"):
        verify_theory_evidence(
            _contract(assumptions=[{"name": "y", "type": "Nat"}]),
            proof,
            destination / "theory_evidence_receipt.json",
        )


def test_changed_log_invalidates_receipt_before_replay(tmp_path, lean):
    proof = tmp_path / "identity.proof"
    proof.write_text("  rfl\n", encoding="utf-8")
    destination = tmp_path / "evidence"
    check_theory_evidence(_contract(), proof, destination, lean_path=lean)
    (destination / "lean_check.log").write_text("forged\n", encoding="utf-8")

    with pytest.raises(TheoryEvidenceError, match="log_sha256"):
        verify_theory_evidence(
            _contract(), proof, destination / "theory_evidence_receipt.json"
        )
